Update Gatby Version for v3 Compatibility
axe312ger/gatsby-plugin-webpack-size pull request #4
Opened 2021-03-07 21:56 UTC by moonmeister

Should come with a major version bump.

2021-03-07 21:58 UTC, moonmeister commented
@axe312ger I see you don't seem to be very busy on this repo. If you need help I'm happy to help merge PRs and publish releases.

2021-03-08 10:21 UTC, axe312ger commented
As the plugin should work with v2 and v3, could you please allow both versions?

2021-03-08 10:26 UTC, axe312ger requested changes

2021-03-08 10:26 UTC, axe312ger commented on package.json
> +    "gatsby": "^3.0.0"
```suggestion
    "gatsby": "^2.0.0 || ^3.0.0"
```

2021-03-08 14:35 UTC, moonmeister commented
Good call. Merged.

2021-03-08 17:05 UTC, merged

2021-03-08 17:06 UTC, axe312ger commented
published as 2.0.1